config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # home page will be rendered in root directory ; example: localhost:3000
  root "pages#home"
  # about page will be rendered in about directory ; example: localhost:3000/about
  get 'about', to: 'pages#about'
  # Define the route for users profile
  get '/u/:id', to: 'users#profile', as: 'user'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
    <%= link_to 'Rails BLog', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to 'Home', root_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Blog', posts_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to 'About', about_path, class:'nav-link' %>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> %>
      </ul>
      <ul class="navbar-nav">
        <%= render 'search/form' %>
        <%= render 'layouts/notifications' %>
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% if current_user %>
  <li class='nav-item dropdown'>
  <a class='nav-link dropdown-toggle' href="#" id='navbarDropdown' role='button' data-bs-toggle='dropdown' aria-expanded='false'>
    <span class='badge rounded-pill bg-danger'>
      <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class='bi bi-suit-heart-fill'></i>
    </span>
  </a>
  <ul class='dropdown-menu dropdown-menu-lg-end' aria-labelledby='navbarDropdown'>
    <% @unread.each do|notification| %>
        <li class='dropdown-item'>
          <%= link_to notification.to_notification.message, notification.to_notification.url %>
        </li>
    <% end %>
    <% if @read.count > 0 && @unread.count > 0 %>
      <li>
        <hr class='dropdown-divider'>
      </li>
      <% elsif @read.count + @unread.count == 0 %>
        <li class='dropdown-item'>
          No notifications available!
        </li>
    <% end %>
    <% @read.each do|notification| %>
      <li class='dropdown-item'>
        <%= link_to notification.to_notification.message, notification.to_notification.url %>
      </li>
    <% end %>
  </ul>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Add Bootstrap CDN %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>